<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="3" total="8" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-28T15:44:45 IST" name="Automation Practice Test Suite" finished-at="2025-08-28T15:48:13 IST" duration-ms="207229">
    <groups>
      <group name="sanity">
        <method signature="LoginTest.login(ui.pojo.ecommerce.User)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" name="login" class="ui.tests.ecommerce.LoginTest"/>
      </group> <!-- sanity -->
      <group name="e2e">
        <method signature="LoginTest.login(ui.pojo.ecommerce.User)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" name="login" class="ui.tests.ecommerce.LoginTest"/>
      </group> <!-- e2e -->
    </groups>
    <test started-at="2025-08-28T15:44:45 IST" name="UI Automation Test Ecommerce" finished-at="2025-08-28T15:48:13 IST" duration-ms="207229">
      <class name="ui.tests.ecommerce.LoginTest">
        <test-method is-config="true" signature="setup(java.lang.String,boolean,boolean,org.testng.ITestResult)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:44:46 IST" name="setup" finished-at="2025-08-28T15:45:19 IST" duration-ms="33357" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest.login(ui.pojo.ecommerce.User)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login(ui.pojo.ecommerce.User)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:45:19 IST" name="login" description="verfify login of users" data-provider="LoginTestDataProvider" finished-at="2025-08-28T15:45:25 IST" duration-ms="5272" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[User [emailAddress=gojat62999@cronack.com, password=passpgpass]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:45:25 IST" name="tearDown" description="Tear Down the browser" finished-at="2025-08-28T15:45:25 IST" duration-ms="725" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String,boolean,boolean,org.testng.ITestResult)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:45:25 IST" name="setup" finished-at="2025-08-28T15:45:41 IST" duration-ms="15955" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest.login(ui.pojo.ecommerce.User)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method retried="true" signature="login(ui.pojo.ecommerce.User)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:45:41 IST" name="login" description="verfify login of users" data-provider="LoginTestDataProvider" finished-at="2025-08-28T15:45:47 IST" duration-ms="5493" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[User [emailAddress=bakomam596@skrak.com, password=password]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Adi boss] but found [Jatin Sharma]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Adi boss] but found [Jatin Sharma]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at ui.tests.ecommerce.LoginTest.login(LoginTest.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:45:47 IST" name="tearDown" description="Tear Down the browser" finished-at="2025-08-28T15:45:48 IST" duration-ms="852" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String,boolean,boolean,org.testng.ITestResult)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:45:48 IST" name="setup" finished-at="2025-08-28T15:46:26 IST" duration-ms="38286" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest.login(ui.pojo.ecommerce.User)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method retried="true" signature="login(ui.pojo.ecommerce.User)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:46:26 IST" name="login" description="verfify login of users" data-provider="LoginTestDataProvider" finished-at="2025-08-28T15:46:31 IST" duration-ms="4484" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[User [emailAddress=bakomam596@skrak.com, password=password]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Adi boss] but found [Jatin Sharma]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Adi boss] but found [Jatin Sharma]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at ui.tests.ecommerce.LoginTest.login(LoginTest.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:46:31 IST" name="tearDown" description="Tear Down the browser" finished-at="2025-08-28T15:46:31 IST" duration-ms="681" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String,boolean,boolean,org.testng.ITestResult)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:46:31 IST" name="setup" finished-at="2025-08-28T15:47:25 IST" duration-ms="54023" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest.login(ui.pojo.ecommerce.User)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method retried="true" signature="login(ui.pojo.ecommerce.User)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:47:25 IST" name="login" description="verfify login of users" data-provider="LoginTestDataProvider" finished-at="2025-08-28T15:47:30 IST" duration-ms="4734" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[User [emailAddress=bakomam596@skrak.com, password=password]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Adi boss] but found [Jatin Sharma]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Adi boss] but found [Jatin Sharma]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at ui.tests.ecommerce.LoginTest.login(LoginTest.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:47:30 IST" name="tearDown" description="Tear Down the browser" finished-at="2025-08-28T15:47:31 IST" duration-ms="691" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String,boolean,boolean,org.testng.ITestResult)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:47:31 IST" name="setup" finished-at="2025-08-28T15:48:08 IST" duration-ms="37084" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest.login(ui.pojo.ecommerce.User)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login(ui.pojo.ecommerce.User)[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:48:08 IST" name="login" description="verfify login of users" data-provider="LoginTestDataProvider" finished-at="2025-08-28T15:48:12 IST" duration-ms="3759" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[User [emailAddress=bakomam596@skrak.com, password=password]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Adi boss] but found [Jatin Sharma]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Adi boss] but found [Jatin Sharma]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at ui.tests.ecommerce.LoginTest.login(LoginTest.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ui.tests.ecommerce.LoginTest@a514af7]" started-at="2025-08-28T15:48:12 IST" name="tearDown" description="Tear Down the browser" finished-at="2025-08-28T15:48:13 IST" duration-ms="664" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ui.tests.ecommerce.LoginTest -->
    </test> <!-- UI Automation Test Ecommerce -->
  </suite> <!-- Automation Practice Test Suite -->
</testng-results>
